<a href="https://colab.research.google.com/github/code-with-Sara/Pytorch-learn/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors** are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors. In fact tensors are merely a generalisation of scalars and vectors; a scalar is a zero rank tensor, and a vector is a first rank tensor.

The rank (or order) of a tensor is defined by the number of directions (and hence the dimensionality of the array) required to describe it. For example, properties that require one direction (first rank) can be fully described by a 3×1 column vector, and properties that require two directions (second rank tensors), can be described by 9 numbers, as a 3×3 matrix. As such, in general an nth rank tensor can be described by 3n coefficients.

In [1]:
import torch
import numpy as np

**Lists**

In [3]:
list = ([1, 2, 3], [4, 5, 6])
print(list)

([1, 2, 3], [4, 5, 6])


**Numpy Arrays**

In [6]:
np1 = np.random.rand(3, 4)
np1

array([[0.07007958, 0.69454279, 0.85620179, 0.01632084],
       [0.50945725, 0.19175733, 0.59221708, 0.24285919],
       [0.09865964, 0.35743352, 0.25882753, 0.65003275]])

In [7]:
np1.dtype

dtype('float64')

**Torch**

In [10]:
tensor_2dim = torch.randn(3,4)
tensor_2dim

tensor([[ 0.8087, -2.0258, -2.0206, -0.1193],
        [-0.1348, -0.5430, -0.2397,  0.0153],
        [-0.7414, -0.3286, -0.9473,  0.4059]])

In [11]:
tensor_3dim = torch.zeros(2,3,4)
tensor_3dim

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#create tensor out of numpy array
mytorch = torch.tensor(np1)
mytorch

tensor([[0.0701, 0.6945, 0.8562, 0.0163],
        [0.5095, 0.1918, 0.5922, 0.2429],
        [0.0987, 0.3574, 0.2588, 0.6500]], dtype=torch.float64)